kysely-org/kysely

src/dialect/mysql/mysql-introspector.ts

Addresses #135. Please see issue for more information.

Fix column casing in MySQL Introspector

---

src/operation-node/drop-index-node.ts
src/operation-node/drop-schema-node.ts
src/operation-node/drop-table-node.ts
src/operation-node/drop-view-node.ts
src/operation-node/operation-node-transformer.ts
src/query-compiler/default-query-compiler.ts
src/schema/drop-index-builder.ts
src/schema/drop-schema-builder.ts
src/schema/drop-table-builder.ts
src/schema/drop-view-builder.ts

Let me know if I did anything incorrectly. closes #143

add cascade to drops in schema module (resolves #143)

---

src/dialect/sqlite/sqlite-adapter.ts
test/node/src/delete.test.ts
test/node/src/insert.test.ts
test/node/src/test-setup.ts
test/node/src/update.test.ts
test/node/src/with-schema.test.ts
test/node/src/with.test.ts

I updated all relevant tests and I believe they should pass.

Enable supportsReturning for sqlite.

---

test/node/src/schema.test.ts

just realized i'd forgot to commit the test cases i added for the cascade stuff... 😅

add cascade tests 

---

src/plugin/camel-case/camel-case-plugin.ts
src/util/object-utils.ts

fix CamelCasePlugin canMap mistakenly mapping ArrayBufferLikes.

---

src/migration/file-migration-provider.ts

caught by eiKulshan on discord.
---
also adds .mts file support while at it.

fix migrationKey calculation keeping dot when .mjs @ `FileMigrationProvider`.

---

CONTRIBUTING.md
README.md

based on a comment by @koskimas on discord.

add `CONTRIBUTING.md`.

---

src/operation-node/select-query-node.ts
src/parser/expression-parser.ts
src/parser/reference-parser.ts
src/query-builder/select-query-builder.ts
src/query-compiler/default-query-compiler.ts
test/node/src/select.test.ts

feat(select/distinctOn): add `RawBuilder` support

---

src/query-builder/delete-query-builder.ts
src/query-builder/insert-query-builder.ts
src/query-builder/select-query-builder.ts
src/query-builder/update-query-builder.ts

chore: fix typo

---

recipes/README.md
recipes/introspecting-relation-metadata.md
src/dialect/database-introspector.ts
src/dialect/mysql/mysql-introspector.ts
src/dialect/postgres/postgres-introspector.ts
src/dialect/sqlite/sqlite-introspector.ts
test/node/src/introspect.test.ts

Closes #270 
Ensure all instrospector return database views and add a boolean isView to the TableMetadata so users can tell them apart.

Introspect views

---

src/operation-node/aggregate-function-node.ts
src/operation-node/operation-node-transformer.ts
src/query-builder/function-module.ts
src/query-compiler/default-query-compiler.ts
test/node/src/aggregate-function.test.ts
test/typings/test-d/function-module.test-d.ts

Closes #250.
---
Also went over `FunctionModule`'s docs.

add `FunctionModule.countAll(...)`.

---

src/query-builder/select-query-builder.ts

fix: change qb to db in innerJoin docs example

---

src/query-builder/select-query-builder.ts

Fix missing quotes in typedoc

---

src/query-builder/insert-query-builder.ts

I noticed theres a duplicate .execute command, must be a typo?

code hints/docs: Remove duplicate .execute from insert onConflict with constraint example.

---

README.md

Neon dialect for Kysely! https://github.com/seveibar/kysely-neon

Add Neon Dialect Link

---

src/dialect/sqlite/sqlite-dialect.ts

Hello, thanks for this library!
Here's a quick MR to fix a code block appearing as text in the documentation.
Thanks

fix code formatting in documentation

---

site/src/pages/index.tsx

Seems like Dax didn't create react.

fix Dax Raad's profile pic in docs.

---

site/docs/dialects.md
site/docs/intro.md
site/docs/migrations.mdx
site/docs/plugins.md
site/docs/recipes/conditional-selects.md
site/docs/recipes/deduplicate-joins.md
site/docs/recipes/excessively-deep-types.md
site/docs/recipes/extending-kysely.md
site/docs/recipes/introspecting-relation-metadata.md
site/docs/recipes/raw-sql.md
site/docs/recipes/schemas.md
site/docusaurus.config.js
site/src/pages/index.tsx

Replaces all links pointing to koskimas's old repo with the new kysely-org

fix broken links in the site

---

README.md
site/docs/recipes/relations.md

First draft of the relations recipe. Only postgres jsonb examples for now.

Add relations recipe

---

README.md
site/docs/recipes/expressions.md
test/node/src/expression.test.ts
test/typings/test-d/expression.test-d.ts

I'm not super happy with the recipe, but better than nothing. I'd like to release the expression builder sooner than later. Any feedback is welcome.

Expression recipe and some simple tests

---

README.md
site/docs/dialects.md
site/docs/installation.md

- aligned dialect list between 3 lists in the codebase.
- reordered lists by popularity (GH stars).
- added Postgres.js dialect.

align 3rd party dialects.

---

README.md

better contributors section @ README.md.

---

README.md

Hey 👋 
- Added discord icon to chat badge to communicate better that we have a discord server.
- Added license badge to improve company adoption.
- Added closed issues, closed PRs, vulnerabilities count, downloads per week badges to communicate maturity and production readiness.
- Added bundle size badge for the serverless/edge/browser crowd worried about bundle sizes.
- Added twitter badge to help us reach more people with announcements.

readme badge pass.

---

src/operation-node/data-type-node.ts
test/node/src/schema.test.ts

add 'bytea' to column data types.

---

package-lock.json
package.json

This PR bumps mysql2 version to latest major (v3).

bump mysql2 to v3.

---

site/src/pages/index.tsx

creator of AdonisJS said nice things.

add Harminder Virk tweet.

---

site/docs/getting-started/Instantiation.tsx

Rename `SQLiteDialect` to the updated `SqliteDialect`

docs: sqlite dialect updated import

---

src/plugin/camel-case/camel-case-plugin.ts
src/plugin/parse-json-results/parse-json-results-plugin.ts
src/util/object-utils.ts

I tested the speed of this thing and it seems to be plenty fast enough. Runtime is a fraction of a millisecond for a result with three levels of nesting and hundreds of objects.

parse json recursively in ParseJsonResultsPlugin

---

src/operation-node/select-query-node.ts
src/parser/set-operation-parser.ts
src/query-builder/select-query-builder.ts
test/node/src/set-operation.test.ts
test/typings/test-d/set-operation.test-d.ts

Support arrays in set operations

---

site/docs/dialects.md

Thank you for the review on https://github.com/kysely-org/kysely/pull/637 @igalklebanov 
This adds it to the third-party dialects list.
Then we'll figure out what to do about that Deno page in the other MR.

Add Deno SQLite to community dialects

---

.github/workflows/test.yml

Bun 1.0 is stable & available
https://bun.sh/blog/bun-v1.0

Test on bun stable

---

site/docs/dialects.md

close https://github.com/kysely-org/kysely/issues/679
1. Hi, I developed a TiDB serverless dialect for kysely here https://github.com/tidbcloud/kysely. Any review is welcomed! Write your comment in the issue
2. It's better to merge this PR in the next week. Because our TiDB serverless driver will be available in the next week
3. I have tested it in our dev environment

Add tidb serverless dialect

---

site/docs/getting-started/Summary.tsx

sqlite doesn't support a truncate statement, but instead supports truncate optimization on a where-less delete statement
https://www.sqlite.org/lang_delete.html
https://www.techonthenet.com/sqlite/truncate.php

add dialect specific truncate snippet for sqlite

---

src/dialect/mssql/mssql-introspector.ts

This fixes https://github.com/kysely-org/kysely/issues/847

Fix MSSQL Table Introspection Duplicate Column

---

src/operation-node/operation-node-transformer.ts
src/operation-node/update-query-node.ts
src/query-builder/update-query-builder.ts
src/query-compiler/default-query-compiler.ts
test/node/src/update.test.ts

Add `LIMIT` operator for update statements

---

src/operation-node/data-type-node.ts
test/node/src/schema.test.ts

Fixes https://github.com/kysely-org/kysely/issues/910

Fix typo on timetz regex

---

site/docs/getting-started/Instantiation.tsx

confirmation [here](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAZQIoBlgwKZwGZQiOAcgCMMZMoBaAZwEcAbdDAZkIG4AoDgOwwHdEqJgAoAlGyA).

fix SQLite import @ getting started.

---

src/query-builder/merge-query-builder.ts
test/node/src/camel-case.test.ts

Hey :wave:
It appears I done goofed and as a result merge queries don't pass through transformation.
Here's a quick fix.

fix merge queries not being transformed.

---

.github/workflows/test.yml
package-lock.json
package.json
test/cloudflare-workers/package-lock.json
test/cloudflare-workers/package.json
test/cloudflare-workers/test.ts

~~Currently blocked by `better-sqlite3` node22 compatibility.~~
CF workers tests stopped working for node18. Let's just skip 'em for node18.

add node22 @ tests.

---

site/docs/recipes/0012-logging.md

This PR adds documentation concerning the possibility to configure logged queries.

add logging documentation page

---

site/docs/getting-started/shared.tsx

Docs now reflect `tedious` support in `Bun`

---

src/dialect/postgres/postgres-introspector.ts
test/node/src/introspect.test.ts

postgres introspection getTables handle partition tables as well.

---

site/docs/getting-started/Querying.tsx

fix mssql createPerson example.

---

src/operation-node/data-type-node.ts

Hi 👋🏻
This pr adds the postgres range types to the schema api.
Built-in types are listed here: https://www.postgresql.org/docs/current/rangetypes.html

feat: add postgres range types

---

src/plugin/deduplicate-joins/deduplicate-joins-transformer.ts
test/node/src/deduplicate-joins.test.ts

Fixes issue https://github.com/kysely-org/kysely/issues/1155

DeduplicateJoinsPlugin preserves order of joins

---

package-lock.json
package.json

Hey :wave:
Pushing this early to spot any issues.

chore: bump TypeScript to 5.6.

---

site/src/pages/index.module.css
site/src/pages/index.tsx

Hey 👋 
This PR fixes the docs' Stackblitz playground not matching the theme in some situations.

docs: fix stackblitz theme out of sync.

---

site/src/components/SectionFeatures/index.tsx

Hey :wave:
This PR goes over the messaging in the docs main page.

docs: rework features list.

---

.github/workflows/test.yml
package-lock.json
package.json
src/query-builder/merge-query-builder.ts
test/node/src/test-setup.ts
test/node/src/transaction.test.ts
test/node/tsconfig.json

Hey :wave:
This is an attempt to truly find out what's our minimum TypeScript version and to have CI find if we're breaking that promise going forward.

ci: test against older TypeScript versions.

---

.github/workflows/test.yml

Hey :wave:
This PR adds Deno 2 to CI tests.

chore: test deno 2.

---

FUNDING.md

Hey 👋 
This PR adds a `FUNDING.md` file explicitly stating we do not accept donations and why.

add FUNDING.md

---

README.md

Hey 👋 
This PR adds curated people sections to the README.
It emphasizes leadership and people who have contributed significantly one way or another.

enhance contribution @ readme.

---

src/migration/migrator.ts
test/node/src/migration.test.ts

Hey :wave:
This PR allows to override the instance-level `disableTransactions` option per-migrate invocation. This will help tool makers support on-the-fly control of this per-command.

feat(migrator): allow disabling transactions in migrate methods.

---

pnpm-lock.yaml
site/docs/execution.mdx
site/docusaurus.config.ts
site/package.json

Hey :wave:
This PR adds Mermaid graphs support to our Docusaurus site.
It also adds a "Execution flow" page that uses sequence graphs to provide an overview of how Kysely works under the hood.

docs: add Execution flow page, and mermaid support.

---

SECURITY.md

Hey 👋 
This PR adds a security policy with some recommendations for supply chain defense, and a way to submit security issues.

chore: add SECURITY.md.
