kysely-org/kysely

src/kysely.ts
If you set `this.#props` and call `super()` in both `if` blocks, when using esbuild it will transform them and put the `this` call first causing runtime failure.
=> Fix issue with esbuild class transform

src/raw-builder/sql.ts
I didn't change it in docs/modules.html, I assume it gets generated automatically...somewhere. When I ran docs:build around 200 files changed so that didn't see mright either
=> docs: fix typo concate -> concat

.github/workflows/test.yml
Node 18 is now the "current" Node version. Add it to CI version matrix.
=> Run CI in Node 18

src/operation-node/operation-node-transformer.ts, test/node/src/schema.test.ts
I was facing a bug when I was using createScheme. I miss the "if not exists" part of compiled query even I use ifNotExists method of CreateSchemaBuilder.
Then I do following fixes: 
- added copy of ifNotExists property in transformCreateSchema
- added copy of orderBy and limit properties in transformDeleteQuery (because of `TEST_TRANSFORMER=1 npm run test` fails)
I've added create/drop schema tests too to prevent regression of this bug in future. Have to be tested with `TEST_TRANSFORMER` environment variable set of course.
Correct me if I'm wrong, SQLLite doesn't support schemas as other DBs do, right? I omit schema tests for it.
=> operation-node-transformer fixed:

src/operation-node/operation-node-transformer.ts, src/util/check-props.ts
It is used in OperationNodeTransformer when nodes are copied
to prevent forgotten properties.
I suggested this change in #111
=> Added checkProps helper

README.md
- "as you can see" -> "as shown"
- "when you update your database to next version" -> "when you update your database to the next version"
- Changed migration-code dependency lines to their own paragraph, as they seem to be a seperate issue than the rest in the paragraph
=> Concision and paragraph breaks in README.md

src/operation-node/data-type-node.ts, test/node/src/schema.test.ts
Fractional Seconds Precision (e.g. `timestamp(n)`) is supported in both [Postgresql](https://www.postgresql.org/docs/current/datatype-datetime.html) and [Mysql](https://dev.mysql.com/doc/refman/8.0/en/fractional-seconds.html) dialects, documented as optional *p* or *fsp* parameter.
Currently, kysely supports date and time data types, without stating *fsp*. Consumers are forced to use raw sql to achieve more accurate columns when creating tables using the schema module.
Database defaults and behavior on insert/update in case *fsp* is omitted are not good enough.
> A value of 0 signifies that there is no fractional part. If omitted, the default precision is 0. 
> 
> Inserting a TIME, DATE, or TIMESTAMP value with a fractional seconds part into a column of the same type but having fewer …
=> adding fractional seconds precision to `db.schema.createTable(name).addColumn(...)`.

src/query-compiler/default-query-compiler.ts
First of all this vulnerability is not completely due to Kysely itself but rather with the way the user of this library might use it.
This fix might seem unnecessary because the vulnerability is not exploitable if Kysely and typescript are used in a safe manner.
But since this fix is really minor, I don't see no disadvantages in making it.
I believe code speaks better so I leave here a scenario in which this vulnerability might be exploited (due to sloppiness of the programmer that might use this library) to prove how easily it could happen and why this fix is important as it eliminates a potential security issue
Imagine we have a table like this
```ts
interface  UserTable = {
id: number;
email: string;
interests: string | null;
authorization:  'full'  |  'restrict'
}
```
and we have 2 …
=> Fix potential security issue

package-lock.json, src/operation-node/create-table-node.ts, src/operation-node/operation-node-transformer.ts, src/query-compiler/default-query-compiler.ts, src/schema/create-table-builder.ts, test/node/src/schema.test.ts
`CREATE TABLE` statement exists in all 3 base dialects ([postgres](https://www.postgresql.org/docs/current/sql-createtable.html), [mysql](https://dev.mysql.com/doc/refman/8.0/en/create-table.html), [sqlite](https://www.sqlite.org/lang_createtable.html)) and their variants (cockroachdb, planetscale, singlestore). Kysely supports compiling such queries using `SchemaModule` (`db.schema.createTable(name)...`).
Dialects and their variants provide abilities to choose table type/scope and configure your table beyond the defaults (e.g. engine, collation, compression, partitioning, etc.). You do this between `CREATE` & `TABLE` keywords and after column, constraint and index scope. Kysely supports some common use cases like temporary tables (`db.schema.createTable(name).temporary()`), and on …
=> adding `db.schema.createTable(name).modifyFront(modifier)` & `db.schema.createTable(name).modifyEnd(modifier)`.

README.md
This PR adds a link to a dialect that uses [PlanetScale's serverless driver for JS](https://github.com/planetscale/database-js).
=> Add PlanetScale serverless driver dialect

src/migration/file-migration-provider.ts
Add a check for a `default` prop when dynamically importing file migrations.
The `FileMigrationProvider` wasn't working in my project which is compiled to `commonjs` and has `esModuleInterop` enabled. So, I edited my local Kysely dependency to add some logging around the imported migration. I saw that the imports where wrapped like this: `{ default: { up: Function, down: Function } }`, so I changed the code to coerce the value from the default property like this:
```js
let migration = await Promise.resolve().then(() => require(
/* webpackIgnore: true */ this.#props.path.join(this.#props.migrationFolder, fileName)));
migration = migration?.default ?? migration;
```
All existing tests have passed for me. I did not write any new tests surrounding this change because I didn't think it was …
=> Coerce file migration from esModuleInterop default prop.

src/dialect/postgres/postgres-adapter.ts
fixes #142.
> The following is truthy in chrome, node 16.x, node 14.x, deno 1.26.x:
>
>```ts
> BigInt('3853314791062309107') === 3853314791062309107n
> ```
>
> And most importantly, astro dev starts successfully after patching this in.
=> fix bigint `n` notation not buildable in some targets.

src/raw-builder/sql.ts
`sql.join` and `sql.ids` don't mutate their arguments, so those arguments should be `readonly`, so that readonly arrays can be passed in without TS complaining.
=> fix(types): make `sql.ids(...)` & `sql.join(...)` arguments readonly

src/query-compiler/default-query-compiler.ts, test/node/src/insert.test.ts, test/node/src/introspect.test.ts, test/node/src/test-setup.ts
Currently, having more than 1 missing column value in `insertInto` value compiles to:
`("hello", "world", nullnull)`
instead of
`("hello", "world", null, null)`
=> fix no separator between default insert values.

src/parser/insert-values-parser.ts, src/parser/update-set-parser.ts, test/typings/test-d/index.test-d.ts, test/typings/tsconfig.json
2nd attempt at closing #170 . #171 missed the mark, changing things deeper than needed.
=> `exactOptionalPropertyTypes` should no longer error when updating/inserting with undefined values in nullable columns.

README.md
I thought it would be nice to showcase `defaultTo` in the PostgreSQL migration example. Personally, I had to look into the discord to figure it out, so I think that an additional line won't hurt.
=> Add additional column in PostgreSQL migration example to showcase defaultTo

src/index.ts, src/query-builder/function-module.ts, src/util/type-utils.ts, test/typings/shared.d.ts, test/typings/test-d/function-module.test-d.ts, test/typings/test-d/infer-result.test-d.ts
closes #221.
Tested autocompletion manually, seems to work now - except for when providing output type in generic - this is a wide typescript issue with partial generics inference and defaults.
=> fix `FunctionModule.max` & `FunctionModule.min` autocompletion.

src/schema/alter-table-builder.ts, src/schema/create-table-builder.ts, test/node/src/schema.test.ts
This is a copy of the approach used on the query builders (e.g. [`SelectQueryBuilder`](https://github.com/koskimas/kysely/blob/9c9acc6a4dbaf90b178397d3ceafdc22d3cb2b46/src/query-builder/select-query-builder.ts#L1471-L1495)), applied to the builders used for creating and altering tables. This addition should make it easier to write reusable functions that operate on those builders!
=> Add `call` to create/alter table statement builder

src/dialect/sqlite/sqlite-introspector.ts
=> fix: trim sql row to remove leading whitespace or newline

src/index.ts, src/operation-node/alter-table-node.ts, src/operation-node/operation-node-transformer.ts, src/query-compiler/default-query-compiler.ts, src/schema/alter-column-builder.ts, src/schema/alter-table-builder.ts, src/schema/column-definition-builder.ts, src/schema/schema.ts, test/node/src/schema.test.ts
- feat(alter-table-node)!: allow multiple alter ops - allow multiple column alterations at `AlterTableNode`
- def-query-compiler: align /w  AlterTableNode
- operation-node-transformer align /w AlterTableNode
- add alter column builder
- remove usages of ColumnDefinitionBuilderInterface
- allow multiple col alterations@alter-table-builder
- rename schema alterTable prop
- added alter-column-builder to index
- added and fixed unit tests
co authored by @igalklebanov 
closes #217
=> feat(alter-table): support multiple column operations

src/dialect/mysql/mysql-driver.ts, src/dialect/postgres/postgres-driver.ts, src/dialect/sqlite/sqlite-driver.ts, src/driver/database-connection.ts, src/index.ts, src/query-builder/delete-query-builder.ts, src/query-builder/insert-query-builder.ts, src/query-builder/insert-result.ts, src/query-builder/update-query-builder.ts, src/query-executor/query-executor-base.ts, src/util/log-once.ts, test/node/src/delete.test.ts, test/node/src/insert.test.ts, test/node/src/log-once.test.ts, test/node/src/update.test.ts
Also:
- Deprecate `QueryResult.numUpdatedOrDeletedRows` and add `QueryResult.numAffectedRows`.
---
~~- [ ] typings tests.~~ tests for `InsertResult` already in place.
---
On MySQL, this field lets consumers know whether an `insert...on duplicate key update` query inserted OR updated some records. Real world scenario, publishing an event following the query, "entity {created | updated}".
> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values. If you specify the CLIENT_FOUND_ROWS flag to the mysql_real_connect() C API function when connecting to mysqld, the affected-rows value is 1 (not 0) if an existing row is set to its current values. …
=> add `numInsertedOrUpdatedRows` to `InsertResult`.

src/operation-node/aggregate-function-node.ts, src/operation-node/operation-node-transformer.ts, src/query-builder/aggregate-function-builder.ts, src/query-builder/where-interface.ts, src/query-compiler/default-query-compiler.ts, test/node/src/aggregate-function.test.ts, test/node/src/postgres-json.test.ts, test/typings/test-d/function-module.test-d.ts
brought up by @thelinuxlich on discord.
Postgres [[1]](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-AGGREGATES) [[2]](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS) & [SQLite](https://www.sqlite.org/windowfunctions.html#the_filter_clause) support `filter` clause when using aggregate functions, with syntax as follows:
```
aggregate_function(...) [filter(where ...)] [over(...)]
```
Its a simple alternative to using `case...when...then...end` inside the aggregate function.
This PR adds `filterWhere`, `filterWhereExists`, `filterWhereNotExists`, `filterWhereRef`, `orFilterWhere`, `orFilterWhereExists`, `orFilterWhereNotExists` & `orFiltereWhereRef` to `AggregateFunctionBuilder`.
---
---
Some things to consider..
- since `where` is …
=> add `filter` clause support at `AggregateFunctionBuilder`.

package.json, src/plugin/deduplicate-joins/deduplicate-joins-plugin.ts, test/node/src/with-schema.test.ts, test/typings/test-d/clear.test-d.ts
I found that some files are not formatted with `npm run prettier` = `prettier --write src/**/*.ts test/**/*.ts`. It is because shell parses glob patterns, not prettier parses them.
If glob pattern arguments are not quoted, the shell parses them and pass parsed strings to the  command. For easy understanding, I replace `prettier` command to `echo`.
```shell
$ echo test/**/*.ts
test/browser/main.ts
test/deno/cdn.test.ts
test/deno/local.test.ts
test/typings/index.d.ts
test/typings/shared.d.ts
```
(I inserted new line manually for readability) This is cause of the problem. I'm using `ubuntu 22.04` with `bash 5.1.16(1)-release`, my bash parses `test/**/*.ts` to a small part of the files. I don't know why.
When I quote the argument,
```shell
$ echo 'test/**/*.ts'
test/**/*.ts
```
It was passed …
=> Fix prettier glob pattern

src/dialect/mysql/mysql-introspector.ts, src/dialect/postgres/postgres-introspector.ts, src/dialect/sqlite/sqlite-introspector.ts, test/node/src/introspect.test.ts
=> Keep column order same as ordinal_position.

src/operation-node/operator-node.ts
Fixes https://github.com/koskimas/kysely/issues/279
In sqlite, a query like ```SELECT * 
FROM posts 
WHERE posts MATCH 'text' 
ORDER BY rank;``` is a valid query
=> Add match to allowed comparison operators

src/migration/migrator.ts
It seems like the `FileMigrationProvider` constructor changed at some point and the jsdoc is not in sync.
=> Fix FileMigrationProvider example

src/parser/expression-parser.ts, test/node/src/raw-sql.test.ts
=> fix `AliasedRawBuilder` being parsed as `ValueNode` instead of `RawNode`.

src/operation-node/operation-node-transformer.ts, test/node/src/camel-case.test.ts
Fixes bug in `transformUsing` method which resulting in table references in a `using` clause not being transformed by the CamelCasePlugin.
=> Fix using node transformation

src/operation-node/delete-query-node.ts, src/parser/table-parser.ts, src/query-creator.ts, test/node/src/delete.test.ts, test/typings/test-d/delete-query-builder.test-d.ts
closes #269 .
---
To consider:
Should we deny empty arrays as inputs at compile-time? (e.g. `QueryCreator.selectFrom`, `QueryCreator.deleteFrom`, `SelectQueryBuilder.groupBy`, etc.
=> add `deleteFrom([t1, t2, ...])` overload.

README.md
This PR adds a link to the libsql/sqld dialect for Kysely that connects to [sqld](https://github.com/libsql/sqld) over [a WebSocket](https://github.com/libsql/hrana-client-ts).
=> Add sqld dialect

src/driver/runtime-driver.ts, src/util/log.ts
This PR is a follow up to [this issue](https://github.com/koskimas/kysely/issues/342).
The change makes it possible to log the compiled query along with its timing in case of error logs. As the issue mentioned, this makes it easier to debug failing queries.
closes #342
=> add compiled query and timing to error logs

recipes/splitting-build-compile-and-execute-code.md, src/kysely.ts, src/query-executor/query-executor.ts, src/util/compilable.ts, test/node/src/execute.test.ts
This PR introduces a shortcut for `Kysely.getExecutor().executeQuery(compiledQuery, queryId)`.
When splitting build, compile and execute code, consumers no longer have to:
- access Kysely's internal `.getExecutor()` method.
- provide a queryId - which is internal.
Additionally: 
- consumer can pass a query builder, it's get compiled under the hood.
- QueryResult gets the correct R type from compiled query when using QueryExecutor's execute query.
=> add `Kysely.executeQuery`.

recipes/splitting-build-compile-and-execute-code.md, src/raw-builder/raw-builder.ts, test/node/src/raw-query.test.ts
This PR allows consumers to compile `RawBuilder`s and pass around their `CompiledQuery`s when splitting build, compile and execute code.
=> add `RawBuilder.compile`.

src/operation-node/create-index-node.ts, src/operation-node/operation-node-transformer.ts, src/operation-node/query-node.ts, src/parser/binary-operation-parser.ts, src/query-compiler/default-query-compiler.ts, src/schema/create-index-builder.ts, test/node/src/schema.test.ts
closes #302.
Adds the ability to create partial indexes in postgres / sqlite.
- only columns known in compile-time (used in `.column`/`.columns`) provide autocompletion,
unknown columns require `sql` template tag to be referred to.
- parameter types are unknown.
- parameters are not allowed (engine throws), so they're turned to literals before parsing.
=> add `.where` & `.orWhere` @ `CreateIndexBuilder`.

site/src/components/Playground.tsx
Pass `allow="clipboard-write" to playground iframe to solve the permission error:
Default kysely version: 0.23.3 -> 0.23.5
=> Fix playground iframe of site.

site/docusaurus.config.js
Adds algolia search using the recommended docusaurus defaults. See https://docusaurus.io/docs/search#using-algolia-docsearch for more information.
=> feat: add algolia search

src/operation-node/data-type-node.ts, test/node/src/schema.test.ts
closes #339 
This PR adds support for `char` datatype for -
- mysql
- postgresql
To achieve that we've added the `char` type to `ColumnDataType` type. This will allow consumers to use type `char`.
- Existing test have been updated to test the functionality.
=> feat: support `char` datatype

src/driver/runtime-driver.ts, src/util/log.ts
We use kysely on AWS lambdas (serverless) with `context.callbackWaitsForEmptyEventLoop = false` option. This helps us keep DB connection pool opened in background when lambda gets reused by AWS.
We want to log specific errors and immediately inform us over Slack if something unexpected happens with a specific query/error. We can setup a pipeline via Cloudwatch/lambda triggers however the use-case can also work for us if `log` function inside `Kysely` class can be `awaited` by Kysely internally.
The reason we cannot use `.then()` inside the logger function for making async network requests is because we run with `callbackWaitsForEmptyEventLoop = false` option where AWS freezes lambda the moment the callback is complete (which will happen unless kysely internally `awaits` the logger to …
=> feature: Make logger support async calls

site/docs/playground.mdx, site/src/components/Playground.tsx
Auto deployments were broken due to SSR crashing in the docs/playground page. Concretely, the setupCode was not being passed.
=> fix: fix vercel auto deployments

README.md, site/src/components/Playground.tsx
1. Update url on README.md
[Old](https://wirekang.github.io/kysely-playground/?p=f&i=-NLp3n_P5fyeQKMQda8n) -> [New](https://kyse.link)
2. Fix clipboard permission error
Since `wirekang.github.io/kysely-playground` redirects to `kyse.link`, `allow="clipboard-write"` won't work anymore with `src="https://wirekang.github.io/...".
1. I bought the domain to make url as short as possible.  
2. I bought it from AWS Route53. It's **5** $/year and I have fixed income.
3. There are no subdomains or other purposes, now or later.
=> docs: update playground url

src/dynamic/dynamic.ts
There appears to be a missing comma in the array of selects passed in as part of the dynamic example code.
This adds it in! 👍
=> Chore(docs): Missing comma in dynamic.ts

src/operation-node/data-type-node.ts, test/node/src/schema.test.ts
=> Added column type binary(${number})

src/operation-node/alter-table-node.ts, src/schema/schema.ts, test/node/src/schema.test.ts
=> Fix alterTable table name parsing

src/operation-node/aggregate-function-node.ts, src/operation-node/operation-node-transformer.ts, src/query-builder/function-module.ts, src/query-compiler/default-query-compiler.ts, test/node/src/aggregate-function.test.ts
as discussed in #397.
This PR adds the ability to use `AggregateFunctionBuilder`'s methods without a built-in aggregate function method (e.g. sum), using `eg.fn.agg(name, [args])` which is inspired by `eb.fn(name, [args])`.
```ts
db.selectFrom('person')
.select(({ fn }) => [
fn.agg<number>('rank').over().as('rank'),
fn.agg<string>('group_concat', ['first_name']).distinct().as('first_names')
])
```
breaking changes:
- internal: aggregate function node structure.
=> add `agg` method @ `FunctionModule` to allow `AggregateFunctionBuilder` usage outside of built-ins.

src/query-builder/function-module.ts, src/util/type-utils.ts, test/typings/test-d/aggregate-function.test-d.ts
Spotted by ddanielcruzz on discord.
```ts
fn("round", [fn.min("ld.price_btc"), sql.lit(5)]).as("floor_price"), // TS does complain ❌
fn("round", [fn.sum("s.volume"), sql.lit(2)]).as("volume"), // TS does not complain ✅
fn("round", [fn.avg("s.avg_price"), sql.lit(5)]).as("avg_price"),// TS does not complain✅
```
When `.min`/`.max` are used as `fn(...)` arguments, their `O` generic defaults to `any` instead of `never` and doesn't allow to use `StringReference` as `.min`/`.max` argument.
The fix replaces `never` with `any` as the "consumer didn't explictly pick an `O` type" default `O` value and everything is fine again.
=> fix `fn.max`/`fn.min` not usable as `fn(...)` arguments.

src/dialect/mysql/mysql-dialect-config.ts, src/parser/expression-parser.ts, src/parser/select-parser.ts, src/parser/table-parser.ts, src/parser/with-parser.ts, src/query-builder/delete-query-builder.ts, src/query-builder/select-query-builder.ts, src/query-builder/update-query-builder.ts, src/schema/create-index-builder.ts, src/util/column-type.ts, src/util/object-utils.ts, src/util/type-utils.ts, test/typings/test-d/with.test-d.ts
Closes #481
Background: TS treats differently simple type alias with generic parameters and type alias which uses conditional type inside. In particular using a conditional type instead of a simple generic doesn't create a new level of nesting. This feature allows us to create deep types without encountering "Type instantiation is excessively deep and possibly infinite" error.
In this PR I added `DrainOuterGeneric` type which transforms original type to conditional, and therefore removes outer generic type wrapper and reduces instantiation depth. Next I replaced every Record with ShallowRecord (the same type but without wrapper). But the key change was to wrap in `DrainOuterGeneric` every "simple" generic type alias located in the return type of query builders methods.
With this …
=> feat: increase fault tolerance to deep types error

src/dialect/postgres/postgres-introspector.ts
So I know this isn't ideal because it's making changes in kysely core for a 3rd party adapter - however it is also the simplest fix
There's some bug in the RDS api that does not like `in` statements used with char fields - it's interpreting the in values as strings instead of chars and failing
Switching it to an orWhere statement fixes the problem
Wanted to throw this up here in case you were willing to accept this change - otherwise we'll have to copy the whole PostgresIntrospector into kysely-data-api to make this one change
=> Workaround obscure RDS Data Api Bug

src/operation-node/alter-column-node.ts, src/schema/alter-column-builder.ts, src/schema/alter-table-builder.ts
Fixes: #467
It was slightly tricky, but I decided that "unwinding" looks the best in terms of clarity of what is happening.
This effectively produces query:
```
ALTER TABLE "x" ALTER COLUMN "y" SET DEFAULT true, ALTER COLUMN "z" DROP NOT NULL, [...]
```
as in Postgres docs. MySQL has exact syntax for chaining ALTER COLUMN, but supports only `drop default` and `set default` operations, so probably nobody will chain those two together, plus alter column usage for MySQL is not properly handled in whole Kysely anyway. I tested MySQL case manually.
---
EDIT: now it just disallows chaining
=> fix: disallow AlterColumn method chaining

.github/workflows/test.yml, package-lock.json, package.json
Node.js LTS is v18, current is v20. v14 was April 30, 2023.
Let's ditch node 14 from our required tests in CI. Replace it with node 20.
This PR also bumps `better-sqlite3` to latest v8 to get node20 compatible binaries.
postrequisites:
- add `run-tests (20.x, 1.19.x)` to required PR checks.
- remove `run-tests (14.x, 1.19.x)` from required PR checks.
=> add node20 to workflows, drop node14, bump better-sqlite3 to v8.

site/docs/getting-started/_types.mdx
the code example in getting started/types part imports Updatable (which doesn't exist) instead of Updateable
=> small mistake in Getting Started/Types

site/docs/getting-started/_types.mdx
Clarifying that automatic generation of the Database interface could lead to a different file of the one shown currently in the documentation, by warning readers of this could help saving some time if they find mismatches, this happened to me while using `prisma-kysely` package.
=> docs(getting started): add clarification to Types section

src/schema/schema.ts
This function call syntax was changed in the breaking change noted in https://github.com/kysely-org/kysely/releases/tag/0.23.0
Thanks!
=> Update outdated alterColumn function call example

site/docs/recipes/introspecting-relation-metadata.md
This PR fixes/improves the following:
The example for Introspecting Relation Metadata has two minor mistakes.
- The pg library does not provide a named export `Pool`, use default import and destructuring instead
- `db().introspection.getTables()` is not callable, needs to be `db.introspection.getTables()`
- Call the `logDatabaseSchema` function at the end of the example to see the results
=> docs: fix introspecting relation metadata example

package-lock.json, package.json, src/query-builder/insert-query-builder.ts, src/query-builder/on-conflict-builder.ts
closes #567.
Seems like a bug in both TypeScript (up to 5.1.3) and in our codebase. We provided an expected return type that can never be matched by call site, and TypeScript never yelled.
And looks like they fixed it in 5.1.6?? 🤷 
`.doUpdateSet` return type:
```ts
OnConflictUpdateBuilder<OnConflictDatabase<DB, TB>, OnConflictTables<TB>>
```
vs.
`.onConflict`'s `callback` argument's return type:
```ts
OnConflictDoNothingBuilder<DB, TB> | OnConflictUpdateBuilder<DB, TB>
```
=> fix `onConflict` compilation errors since TS 5.1.6.

src/operation-node/common-table-expression-node.ts, src/operation-node/operation-node-transformer.ts, src/parser/join-parser.ts, src/parser/with-parser.ts, src/query-builder/cte-builder.ts, src/query-compiler/default-query-compiler.ts, src/query-creator.ts, test/node/src/with.test.ts, test/typings/test-d/with.test-d.ts
The first argument of `with` can now be a callback that's given a CTE builder. The CTE builder can be used to create the common table expression statement.
```ts
db.with(
(cte) => cte('jennifers').materialized(),
(db) =>
db
.selectFrom('person')
.where('first_name', '=', 'Jennifer')
.select(['first_name', 'last_name as ln', 'gender'])
)
.selectFrom('jennifers')
.select(['first_name', 'ln'])
.execute()
```
The syntax feels natural and this way `as materialized` is "in the correct place" between the name and the query. But we're introducing a new way to do things here and I'm not sure if this a good precedent for future development, or just something completely disjoint from all other builders.
Putting the CTE builder last, after the query, also feels bad since it's in the wrong place. But …
=> Support materialized CTEs using CTE builder

src/query-builder/json-path-builder.ts, test/typings/shared.d.ts, test/typings/test-d/json-traversal.test-d.ts
Hey 👋 
We haven't handled dictionaries with wide `string` keys (`Record<string, T>`) in phase 1 (#440).
The type-safe way should be to infer `Nullable<T>` here, since there's no indication `key('blabla')` exists in the JSON object.
This PR handles this, and adds some typings tests.
=> when traversing `Record<string, T>`, infer output type as `Nullable<T>`.

scripts/generate-site-examples.js, src/expression/expression-builder.ts, src/parser/parse-utils.ts, src/query-builder/delete-query-builder.ts, src/query-builder/having-interface.ts, src/query-builder/select-query-builder.ts, src/query-builder/where-interface.ts, src/query-creator.ts, src/raw-builder/raw-builder.ts, src/raw-builder/sql.ts
My guess is that these two classes are most used ones (in addition to Kysely) in customer code. By turning them to interfaces we get rid of some of the type mismatches when there are multiple versions of Kysely.
=> Convert `SelectQueryBuilder` and `RawBuilder` to interfaces

src/expression/expression-builder.ts, src/expression/expression-wrapper.ts, src/index.ts, src/parser/expression-parser.ts, src/query-builder/aggregate-function-builder.ts, src/query-builder/delete-query-builder.ts, src/query-builder/having-interface.ts, src/query-builder/join-builder.ts, src/query-builder/on-conflict-builder.ts, src/query-builder/select-query-builder.ts, src/query-builder/update-query-builder.ts, src/query-builder/where-interface.ts, src/schema/create-index-builder.ts, test/node/src/raw-sql.test.ts, test/node/src/where.test.ts, test/typings/test-d/where.test-d.ts
There were couple of issues in filter expressions this PR fixes:
1. Filters allowed all kinds of expressions, not just boolean expressions.
2. Filters didn't allow subqueries that select a boolean value.
This PR can be considered a breaking change since people will need to add explicit types for raw sql filters if they didn't have them already. On the other hand this PR fixes a typing bug, so it's open to interpretation.
=> Support boolean subqueries in addition to boolean expressions in filters

src/expression/expression-builder.ts, test/node/src/expression.test.ts, test/node/src/where.test.ts, test/typings/test-d/expression.test-d.ts
=> Add `lit` method to expression builder

src/expression/expression-builder.ts, src/operation-node/operator-node.ts, src/query-builder/having-interface.ts, src/query-builder/join-builder.ts, src/query-builder/where-interface.ts, src/schema/alter-table-builder.ts, src/schema/column-definition-builder.ts, test/node/src/expression.test.ts, test/typings/test-d/expression.test-d.ts
Don't know if this is a good DX. Feel free to shoot this down.
=> Add between method to expression builder

package.json, site/docs/recipes/relations.md, src/helpers/mysql.ts, src/helpers/postgres.ts, src/helpers/sqlite.ts, test/node/src/json.test.ts
I have tested the queries in the comments—those SQLite queries work as intended.
Unfortunately, I could not use the PostgreSQL helpers due to `Parse error: no such column: agg`.  It seems that SQLite still expects column names.
I have also modified the kysely functions to match the SQLite queries.
The schema used in the examples is:
```sql
CREATE TABLE IF NOT EXISTS "person" ("id" integer primary key, "first_name" text not null, "last_name" text, "gender" text not null, "created_at" text default CURRENT_TIMESTAMP not null);
CREATE TABLE IF NOT EXISTS "pet" ("id" integer primary key, "name" text not null unique, "owner_id" integer not null references "person" ("id") on delete cascade, "species" text not null, is_favorite boolean);
CREATE INDEX "pet_owner_id_index" on "pet" ("owner_id"); …
```
=> feat: kysely/helpers/sqlite

src/util/type-utils.ts, test/typings/shared.d.ts, test/typings/test-d/select.test-d.ts
PR to address part of #577. The new test here failed previously, but passes with this change to `NarrowPartial`. There weren't any previous tests for `NarrowPartial`, so let me know if there are any you'd like me to add to make sure that this didn't break anything.
=> types: preserve object type unions in $narrowType

src/expression/expression-builder.ts, src/operation-node/select-query-node.ts, src/parser/parse-utils.ts, src/plugin/camel-case/camel-case-plugin.ts, src/query-compiler/default-query-compiler.ts, src/query-creator.ts, test/node/src/select.test.ts, test/typings/test-d/expression.test-d.ts, test/typings/test-d/select-no-from.test-d.ts, test/typings/test-d/select.test-d.ts
This has been requested a lot. Let's hope knex peeps don't get too confused.
`select` returns `SelectQueryBuilder` that has join methods that are not supported without a `from` clause. The alternative was copy-pasting the whole `SelectQueryBuilder` without the join methods. I think this is the lesser evil.
=> Support select queries without from clause

src/expression/expression-builder.ts, src/parser/value-parser.ts, src/query-builder/function-module.ts, test/node/src/array.test.ts, test/node/src/expression.test.ts, test/node/src/where.test.ts, test/typings/shared.d.ts, test/typings/test-d/expression.test-d.ts
=> Add `any` function to the function module

src/operation-node/operator-node.ts
This PR adds the [array overlap operator](https://www.postgresql.org/docs/current/functions-array.html) (`&&`) to the list of allowed comparison operators.
`&&` has been added in PostgreSQL 8.2, along with the `@>` and `<@` comparison operators, which are already supported by Kysely.
=> Add array overlap operator (`&&`) to `COMPARISON_OPERATORS`

src/expression/expression-builder.ts, src/index.ts, src/operation-node/operation-node-transformer.ts, src/operation-node/operation-node-visitor.ts, src/operation-node/operation-node.ts, src/operation-node/tuple-node.ts, src/parser/select-parser.ts, src/parser/tuple-parser.ts, src/query-builder/select-query-builder.ts, src/query-compiler/default-query-compiler.ts, src/util/column-type.ts, src/util/type-utils.ts, test/node/src/select.test.ts, test/node/src/where.test.ts, test/typings/test-d/expression.test-d.ts
This PR adds tuple support. After trying out a bunch of options, I ended up with a function overload approach up to tuples of length five. There's also a partially unsafe `$asTuple` function in `SelectQueryBuilder` that I don't love.
The reason for my choices basically boils down to the fact that typescript doesn't allow the index of a type in an union to be observed. They've stated in some issues that it will never be observable.
Because of this, there's no (sane) conversion from an object to a tuple, which is why the `$asTuple` method is necessary. If you google this, there is a solution, but it takes around 3 gigabytes of memory to convert a single object to a tuple, so that's a hard no-no.
Using function overloads instead of a recursive type (like the one in coalesce) is also due to …
=> Support tuples

src/schema/alter-table-builder.ts, test/node/src/schema.test.ts
=> Add addPrimaryKeyConstraint for AlterTableBuilder

src/dialect/postgres/postgres-dialect-config.ts
I was browsing the [PostgresPool](https://kysely-org.github.io/kysely-apidoc/interfaces/PostgresPool.html) section of the documentation and noticed that the link to the node-postgres pool API doc was 404ing as it had `/api/` instead of `/apis/` in the link.
Thought I'd submit a quick PR to fix it.
Thanks!
=> fix node-postgres `pool` link

src/kysely.ts
We have a complex schema definition with over 130 tables, and type resolution when passing around a `Transaction` object was very slow because of this:
`type SlowTypeResolution = Transaction<KyselySchema> extends Kysely<KyselySchema> ? true : false`
E.x.
```ts
const runDirectlyOrInTransaction = async (db: Kysely<KyselySchema>) => {
await db.selectFrom("foo").selectAll().execute()
}
await kysely.transaction().execute(async trx => {
await runDirectlyOrInTransaction(trx)
})
```
According to a TS trace, the hotspot was the `.withTables()` generic.
With this fix, type resolution time on our project went from > 30s to 4s.
=> Simplify .withTables() return type

site/docs/recipes/relations.md
Relations docs had a duplicated word "rows". This fixes that typo
=> Fixing a typo in the relations docs

site/docs/dialects.md
Xata is a serverless data platform built on top of PostgreSQL, as a new feature we are now exposing SQL over HTTP and we have built a driver for Kysely.
Implementation: https://github.com/xataio/client-ts/blob/main/packages/plugin-client-kysely/src/driver.ts
=> Add Xata as a dialect

site/docs/recipes/splitting-build-compile-and-execute-code.md
In the site documentation there is a recipe for ["Splitting build, compile and execute code"](https://kysely.dev/docs/recipes/splitting-build-compile-and-execute-code#cold-kysely-instances) which is importing a non-existing export for `PostgresCompiler`.
```
'"kysely"' has no exported member named 'PostgresCompiler'. Did you mean 'PostgresQueryCompiler'?
```
I don't know where this is coming from, perhaps from an earlier version of Kysely, but either way I think that part is no longer needed.
As a side note, I think this line should include a generic parameter passed to `Kysely`, or maybe just an `any`? Not sure what the best practice is, I guess it depends what one is trying to achieve.
https://github.com/kysely-org/kysely/blob/ce1502d0765b7220109cdb8aff32c822beebadf2/site/docs/recipes/sp …
=> docs: fix "splitting build, compile and execute code" recipe

site/docs/recipes/splitting-build-compile-and-execute-code.md
Follow up from #662. As per your advice that it would be better if all the examples shown in this recipe worked without unintentional errors, I've added a minimal `Database` interface as seen in other places throughout the documentation.
I was very tempted to leave a note about instantiating the `Kysely` instance with an `any` as a generic type parameter, but ultimately opted against, since it might be conflicting with later examples on this page which make use of `InferResult`.
Cheers!
=> docs: improve "splitting build, compile and execute code" recipe

src/driver/single-connection-provider.ts, test/node/src/transaction.test.ts
The error stack was losing context because the Promise chain [must be unbroken](https://cloudreports.net/v8-zero-cost-async-stack-traces/) for the error context to correctly work.
E.x. on an internal codebase:
```ts
await kysely.transaction().execute(async trx => {
// generates invalid query
await trx.selectFrom("foo").where("foo_id", 'in', []).execute()
})
```
before:
after:
(`tests/db/tests/db/postgres-error-stacks.test.ts` is the path to the file that throws)
Added test was previously failing.
=> Fix Node.js stack traces when code in a transaction throws

site/docs/dialects.md
We are releasing the serverless driver today. The name is changed to TiDB Cloud serverless driver.
=> Rename tidb serverless driver to tidb cloud serverless driver

src/driver/runtime-driver.ts, src/util/log.ts, test/node/src/log-once.test.ts, test/node/src/logging.test.ts
closes #743.
This is better than the suggested solution in the comment section. If we moved query logging to the `try` body, we'd catch errors in user's logging logic. User has all the context necessary to handle his logic's exceptions and print necessary errors.
Regarding timing mismatch, not much we can do about it.
Went ahead and fixed `defaultLogger`'s error handling when not `Error` - it was printing `[object Object]`.
=> fix: query and error logging both occur on error.

src/query-builder/select-query-builder.ts, test/typings/test-d/with.test-d.ts
closes #785.
This is voodoo, but works. Nothing else I tried did - the result of the inner `$if` was always `{ [x: string]: any }[]`.
=> fix: `$if` inside `with` is `{ [x: string]: any }[]`.

package.json, src/helpers/mssql.ts, test/node/src/json.test.ts, test/node/src/test-setup.ts
Hey :wave:
This PR adds `jsonArrayFrom`, `jsonObjectFrom` and `jsonBuildObject` helpers for MS SQL Server (mssql).
Just like with SQLite, it requires using `ParseJSONResultsPlugin`.
Unlike other engines, there are no JSON aggregate functions, but an entire [`for json` clause](https://learn.microsoft.com/en-us/sql/relational-databases/json/solve-common-issues-with-json-in-sql-server?view=sql-server-ver16#create-a-nested-json-structure).
=> add mssql json helpers.

src/query-builder/function-module.ts, test/typings/test-d/aggregate-function.test-d.ts
closes #764.
The current signature of `eb.fn.max` is too complex. The main variant combines 2 separate cases into 1 and results in this awkward type error due to a "no generic given" check that's failing for some reason in the complex example. I've split the cases to 2 variants - one where no `O` type is given, and one where `O` is given and we need to verify it's aligned with `C`'s column type.
Removed some pointless `extends` in internal types so we could see better compile-time performance.
Removed the complex "no generic given" checks from the most used case, so might improve stuff as well.
=> fix: `ExpressionBuilder.fn.max`/`ExpressionBuilder.fn.min` signature type complexity breaks in complex `with` example.

src/dialect/mssql/mssql-introspector.ts
After bumping to version 0.27.0, support for node 14 is missed.
=> Fix regression Node 14

site/docs/migrations.mdx, src/migration/migrator.ts, test/node/src/migration.test.ts
This add an `allowUnorderedMigrations` option to [`MigratorProps`](https://github.com/kysely-org/kysely/blob/1538485c/src/migration/migrator.ts#L598). The options are `true` or `false`, with `false` being the default.
When true, it will allow new migrations to be run even if they are added alphabetically before ones that have already executed.
When false, it will give an error if your migration files are not alphabetically ordered in the same order that they were executed in the database. 
Closes #697
If a team has multiple developers, two people can create migrations asynchronously on separate branches. With strict ordering, those migration files have to be merged in the right order (or renamed before merging) or else Kysely will throw an error when trying to migrate them.
Example:
- …
=> Add `allowUnorderedMigrations` option to Migrator

src/dialect/database-introspector.ts, src/dialect/mssql/mssql-introspector.ts, src/dialect/mysql/mysql-introspector.ts, src/dialect/postgres/postgres-introspector.ts, src/dialect/sqlite/sqlite-introspector.ts, test/node/src/introspect.test.ts, test/node/src/schema.test.ts, test/node/src/test-setup.ts
=> introspect column comments 

src/operation-node/delete-query-node.ts, src/operation-node/query-node.ts, src/query-builder/delete-query-builder.ts, src/query-builder/insert-query-builder.ts, src/query-builder/select-query-builder.ts, src/query-builder/update-query-builder.ts, test/node/src/clear.test.ts, test/typings/test-d/clear.test-d.ts
- Include `clearReturning()` method in `InsertQueryBuilder`, `UpdateQueryBuilder` and `DeleteQueryBuilder`
- Include `clearLimit()` and `clearOrderBy()` in `DeleteQueryBuilder`
=> implement additional query builder clear methods

src/operation-node/data-type-node.ts
Add missing _smallint_ type support for `addColumn()`
=> Just add missing smallint support for addColumn() (SIMPLE_COLUMN_DATA_TYPES)

src/expression/expression-builder.ts
This PR fixes a small typo on the example detailing the case function.
=> Correct spelling mistake in the case example

package-lock.json, package.json, site/docs/examples/JOIN/0030-complex-join.js, site/docs/examples/JOIN/0030-complex-join.mdx, src/query-builder/select-query-builder.ts
Hello,
when I read the docs I failed to understand how to do OR expressions.
> You can do all the same things with the
`on` method that you can with the corresponding `where` method
The hint at the `where` documentation was not sufficient for me (that's more a me issue though).
So I included a little more information about the options provided by `on`.
=> [Docs] Update complex join example to better illustrate the options available (symmetry with `where`)

src/operation-node/column-definition-node.ts, src/operation-node/operation-node-transformer.ts, src/query-compiler/default-query-compiler.ts, src/schema/column-definition-builder.ts, test/node/src/schema.test.ts
Implements `ADD COLUMN IF NOT EXISTS`.
If I'm not mistaken this is only supported by Postgres (https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-DESC-ADD-COLUMN).
Let me know if there's something to improve upon.
=> feat: add 'add column if not exists' for postgres

src/operation-node/select-query-node.ts, src/query-builder/select-query-builder.ts, test/node/src/clear.test.ts
Adds the option to remove group by clause from `SelectQueryBuilder` using `clearGroupBy()` (as discussed in https://discord.com/channels/890118421587578920/1073948476590792786/threads/1221117943081996429)
I've only added a single node test, should I add additional ones for other environments? 
---
Unrelated to this PR in particular: I had some issues making tests for mssql work. After following https://github.com/kysely-org/kysely/issues/906 it worked. Maybe we should add this to the Contribution Guidelines? Additionally I've had issues with prettier modifying indentation and tsc complaining about `Duplicate identifier 'Prepend'` – I had to manually disable lib checks. I'm running on node v20.8.0 and npm 10.1.0
=> Added `clearGroupBy()`

.github/workflows/test.yml
Hey 👋 
`docker-compose [command]` no longer works in GitHub Actions.
https://docs.docker.com/compose/migrate/
=> migrate to docker compose v2.

src/query-compiler/default-query-compiler.ts, test/node/src/merge.test.ts
closes #939
This seems to fix an issue I had when having a `whenMatched` and a `whenNotMatched` in a single merge statement within MSSQL.
All tests passed locally, but I mostly just copied down a different test with a slight addition, so feel free to make any suggestions or changes if it can be improved.
Thanks
=> Updating visitMergeQuery to join `WhenNode`s with a space

.github/workflows/test.yml
Hey 👋 
Just bumping action versions and runtime versions.
Also re-enabled bun test.
=> bumping actions.

package-lock.json, src/plugin/parse-json-results/parse-json-results-plugin.ts, test/node/src/parse-json-results-plugin.test.ts
Hey :wave:
This PR offers a way to avoid nasty runtime errors when result objects/arrays have non-writable props when parsing using `ParseJSONResultsPlugin`.
The default strategy is `'in-place'` (similar to how the plugin behaves in latest version).
In large objects/arrays, the new `create` strategy might significantly differ in memory consumption, as it fills new objects/arrays instead of mutating the existing ones.
=> add `objectStrategy` option that allows to not mutate result objects/arrays @ `ParseJSONResultsPlugin`.

site/docs/getting-started/Instantiation.tsx
=> fixed docs for deno

site/docs/recipes/0001-relations.md
The way kysely uses json aggregate functions in the MySQL helpers is only supported since version 8.0.14 and not supported in MariaDB. This pull requests adds this information to the documentation.
References:
- [MySQL 8.0.14 changelog](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-14.html#mysqld-8-0-14-optimizer) 
- [open ticket for MariaDB](https://jira.mariadb.org/browse/MDEV-19078)).
- [discord discussion](https://discord.com/channels/890118421587578920/1182713092161949866)
=> Added MySQL and MariaDB support information for relation recipes

docker-compose.yml
> The top-level version property is defined by the Compose Specification for backward compatibility. It is only informative and you'll receive a warning message that it is obsolete if used.
https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
=> remove docker-compose file version.

src/kysely.ts
This PR corrects an apostrophe-possessiveness mistake: it's --> its.
=> Fix typo (it's --> its)

src/operation-node/operator-node.ts
Added Postgres '?|' comparison operator.
closes: #1002
=> feat: add '?|' comparison operator

site/src/components/SectionFeatures/index.tsx
[Dialects list](https://kysely.dev/docs/dialects) mentions only D1, so I guess this might be a typo.
=> Docs: Fix typo

src/schema/alter-column-builder.ts, src/schema/alter-table-builder.ts
Hey 👋 
I've checked the reproduction repository provided at https://github.com/kysely-org/kysely-ctl/issues/26, and it appears to be that `preventAwait`ing `AlterColumnBuilder` outside of its own file was causing this issue in the given CommonJS setup.
I believe the `preventAwait` being in the wrong file was caused by an incomplete extraction refactor, and should be in `AlterColumnBuilder`'s file anyway.
=> move `preventAwait` to `alter-column-builder`.ts.

src/operation-node/operator-node.ts
https://www.postgresql.org/docs/current/spgist-builtin-opclasses.html#SPGIST-BUILTIN-OPCLASSES-TABLE
There are a lot more operators as well that are arguably even more esoteric, not sure this can scale forever but.
see #891 and #1012. worth noting that `sql<boolean>` doesn’t currently work, but what you can do is
```ts
eb("tag", sql`^@`, ".").$castTo<boolean>()
```
=> feat: add the starts-with postgres comparison operator

src/dialect/mssql/mssql-dialect-config.ts, src/dialect/mssql/mssql-driver.ts, test/node/src/disconnects.test.ts
=> handle connection errors @ `MssqlDriver`.

site/docs/recipes/0010-extending-kysely.md
=> docs: fix `values` example no compiling.

src/query-builder/merge-query-builder.ts, test/typings/test-d/infer-result.test-d.ts
Hey :wave:
This PR fixes `InferResult` not working for merge queries - currently always infers `never`.
=> fix `InferResult` not working for merge queries.

src/query-builder/merge-query-builder.ts, src/util/infer-result.ts, test/typings/test-d/infer-result.test-d.ts
Hey :wave:
Right now, `InferResult` wrongfully outputs a singular type, despite queries actually having a plural result type when executed.
This PR makes it plural instead.
This will enable simpler types for when we implement batch execution.
=> `InferResult` should output plural.

src/dialect/mssql/mssql-dialect-config.ts, src/dialect/mssql/mssql-driver.ts, test/node/src/test-setup.ts
This PR is part of https://github.com/kysely-org/kysely/issues/1061.
Adds a new optional `resetConnectionOnRelease` config option to `config.tedious` that controls if the underlying tedious `reset` function is called when a connection is released back to the connection pool. The value defaults to true to maintain current behavior.
Adds new optional `validateConnections` argument to `config.tarn` that controls if tarn will execute a query to validate a connection before it is acquired. Defaults to `true` to maintain current behavior.
This is non-breaking change that will require no action for those currently using the MSSQL dialect, as it maintains current behavior.
=> Add additional config options to MSSQL dialect

site/docs/examples/update/0010-single-row.js, site/docs/examples/update/0020-complex-values.js, site/docs/examples/update/0030-my-sql-joins.js, site/docs/examples/update/0030-my-sql-joins.mdx, site/package-lock.json, src/operation-node/update-query-node.ts, src/parser/select-parser.ts, src/parser/update-set-parser.ts, src/plugin/with-schema/with-schema-transformer.ts, src/query-builder/update-query-builder.ts, src/query-compiler/default-query-compiler.ts, src/query-creator.ts, test/node/src/update.test.ts
Adds support for queries like this:
```sql
update
person,
pet
set
person.first_name = ?,
pet.name = ?
where
person.id = pet.owner_id
and person.name = ?
```
This kind of queries are supported by (at least) MySQL. As discussed in #192 we can't really make the join methods work with both MySQL and PostgreSQL since postgres joins add tables to the `TB` generic and MySQL would need to add to both `UT` and `TB` generics.
The `set({ first_name: 'foo' })` version of the `set` method doesn't support table qualified references. The users need to use the `set('table.column', value)` version.
=> Support update table1, table2, ... query support. Closes #192

site/docs/recipes/0001-relations.md
I don't know why it took so long to figure out that this is how we should tell people to write their relation helper functions:
```ts
function pets(foreignKey: Expression<string>) {
return jsonArrayFrom(
db.selectFrom('pet')
.select(['pet.id', 'pet.name'])
.where('pet.owner_id', '=', foreignKey)
.orderBy('pet.name')
)
}
```
Instead of the old suggestion:
```ts
function pets(eb: ExpressionBuilder<DB, 'person'>) {
return jsonArrayFrom(
eb.selectFrom('pet')
.select(['pet.id', 'pet.name'])
.whereRef('pet.owner_id', '=','person.id')
.orderBy('pet.name')
)
}
```
The former only takes in the dependencies (the foreign key) as an argument and provides just as much type-safety as the old way.
The old way had a number of issues: It specified the exact `ExpressionBuilder` type, which doesn't work if …
=> Improve relations recipe

site/docs/recipes/0006-expressions.md
Use the new suggested way to create helper functions in the expressions recipe.
=> Improve expressions recipe

src/expression/expression-builder.ts, src/parser/delete-from-parser.ts, src/parser/merge-into-parser.ts, src/parser/select-from-parser.ts, src/parser/table-parser.ts, src/parser/update-parser.ts, src/query-creator.ts, test/typings/test-d/generic.test-d.ts, test/typings/test-d/huge-db.test-d.ts, test/typings/test-d/kysely-any.test-d.ts
This speeds up type checks with huge database interfaces.
The added type test case took 12 seconds to check before the fixes and about 0.4 seconds after the fixes.
Once again, I have no idea why things got faster, but it's related to function overloads. Squashing all overloads of `selectFrom`, `updateTable`, `mergeInto` and `deleteFrom` into a single signature fixes the perf issues 🤷
This is a slightly breaking change. It breaks some generics use cases, but those were pretty much unusable already anyways.
=> Speedup types with huge databases. Fixes #867

example/README.md, src/kysely.ts, src/plugin/deduplicate-joins/deduplicate-joins-plugin.ts, src/query-builder/select-query-builder.ts, src/query-creator.ts
some links were pointing to what I'm assuming is the previous repository for kysely
=> docs: updated outdated links

src/query-builder/json-path-builder.ts, test/typings/test-d/json-traversal.test-d.ts
=> Updated TraversedJSONPathBuilder.$castTo and .$notNull to support chaining with .as()

src/raw-builder/sql.ts
=> fix: Raw builder typos

package.json, scripts/copy-interface-documentation.js, src/dialect/mssql/mssql-dialect-config.ts, src/dialect/mssql/mssql-driver.ts, src/dialect/mysql/mysql-driver.ts, src/dialect/postgres/postgres-driver.ts, src/dialect/sqlite/sqlite-driver.ts, src/driver/driver.ts, src/driver/dummy-driver.ts, src/driver/runtime-driver.ts, src/kysely.ts, src/parser/savepoint-parser.ts, src/query-executor/query-executor-base.ts, src/util/provide-controlled-connection.ts, test/node/src/controlled-transaction.test.ts
closes #257.
This PR adds some optional savepoint-related methods to drivers - need to make sure we don't introduce a breaking change here!
A new `ControlledTransaction` that allows manual `commit`, `rollback` and savepoint-related commands.
```ts
const trx = await db.startTransaction().execute()
try {
const moshe = await trx
.insertInto('person')
.values({ name: 'Moshe' })
.returning('id')
.executeTakeFirstOrThrow()
const trxAfterFoo = await trx.savepoint('foo').execute()
try {
const bone = await trxAfterFoo
.insertInto('toy')
.values({ name: 'Bone', price: 1.99 })
.returning('id')
.executeTakeFirstOrThrow()
await trxAfterFoo
.insertInto('pet')
.values({ 
owner_id: moshe.id, 
name: 'Lucky', 
favorite_toy_id: bone.id 
})
.execute()
} catch (error) {
await …
```
=> add `ControlledTransaction`.

site/docusaurus.config.ts, site/src/components/Playground.tsx, site/src/components/SectionFeatures/index.tsx, site/src/css/custom.css, site/src/pages/index.tsx
Hey :wave:
closes #1176.
This PR adds light mode support to the docs site.
=> docs: support light mode.

src/kysely.ts, test/node/src/async-dispose.test.ts, test/node/tsconfig.json, tsconfig-base.json
Hey 👋 
This PR introduces `await using db = new Kysely(...)` support. Under the hood, it calls the `destroy` function when the scope in which `using` was used is exited.
`using` is part of TypeScript since version 5.2 was released in August 2023 (more than a year ago).
According to `npm` stats:
`typescript` has 59,208,821 weekly downloads.
`typescript`@5.6.2 has 10,367,140 weekly downloads.
`typescript`@5.5.4 has 5,269,636 weekly downloads.
`typescript`@5.5.3 has 1,986,815 weekly downloads.
`typescript`@5.5.2 has 793,512 weekly downloads.
`typescript`@5.4.5 has 4,832,241 weekly downloads.
`typescript`@5.4.4 has 272,520 weekly downloads.
`typescript`@5.4.3 has 551,093 weekly downloads.
`typescript`@5.4.2 has 1,258,707 weekly downloads.
`typescript`@5.3.3 has 4,330,332 weekly downloads. …
=> `await using kysely = new Kysely()` support.

site/docs/getting-started.mdx, site/docs/getting-started/_prerequisites.mdx
Hey :wave:
This PR adds a prerequisites section to the "getting started" page in the docs site.
TypeScript 4.6+ and `strict: true` are the current requirements.
=> docs: add prerequisites section in "getting started".

package-lock.json, package.json
Hey :wave:
This PR adds a `@arthetypeswrong/cli` check. It ensures the conditional exports in `package.json` are correct for dual-module publishing.
=> chore: add conditional exports test.

.github/workflows/preview.yml, .github/workflows/test.yml, package-lock.json, package.json
Hey :wave:
This PR adds [`pkg-pr-new`](https://github.com/stackblitz-labs/pkg.pr.new). It is a `stackblitz` sponsored project that enables continuous preview releases for libraries, without publishing to NPM.
This allows maintainers and consumers to preview changes, like bug fixes, new features, etc. without waiting for the maintainers to publish to NPM.
The official GitHub application has already been installed for all the organization's repositories.
We should now start seeing PR comments with package URL anyone can install using `npm i` and a `stackblitz` project based on `/example`.
=> chore: add continuous preview releases.

deno.check.d.ts, src/schema/alter-table-add-index-builder.ts, src/schema/column-definition-builder.ts, src/schema/create-table-builder.ts, src/util/column-type.ts, src/util/require-all-props.ts, src/util/type-utils.ts
Hey 👋 
This PR fixes some erroneous JSDocs, and also adds some examples.
=> chore: fix jsdoc errors and add some examples, pt. 1.

deno.check.d.ts, src/query-builder/function-module.ts, src/query-builder/insert-query-builder.ts, src/query-builder/insert-result.ts, src/query-builder/merge-query-builder.ts, src/query-builder/on-conflict-builder.ts, src/query-builder/output-interface.ts, src/query-builder/returning-interface.ts, src/query-builder/select-query-builder.ts, src/query-builder/update-query-builder.ts, src/query-builder/where-interface.ts, src/query-creator.ts, src/raw-builder/raw-builder.ts, src/raw-builder/sql.ts, src/schema/alter-column-builder.ts
Hey :wave:
This PR fixes some erroneous JSDocs, and also adds some examples.
=> chore: fix jsdoc errors and add some examples, pt. 2.

src/kysely.ts
I needed to know whether I can `try … catch …` exceptions that are thrown in the callback to `db.transcation().execute(…)` or whether they get swallowed. The docs are not clear about this.
I added a few words to the docs to clarify. (This is the [relevant code](https://github.com/kysely-org/kysely/blob/25b6715af7f941e4fb455f63fc2dd5584965b4a3/src/kysely.ts#L572).)
=> docs: clarify that after rolling back a transaction the exception gets thrown again

deno.check.d.ts, deno.check.json, src/dialect/dialect-adapter.ts, src/dialect/mssql/mssql-adapter.ts, src/dialect/mssql/mssql-dialect-config.ts, src/dialect/mysql/mysql-adapter.ts, src/dialect/postgres/postgres-adapter.ts, src/dialect/postgres/postgres-dialect-config.ts, src/dialect/sqlite/sqlite-adapter.ts, src/driver/dummy-driver.ts, src/dynamic/dynamic.ts, src/expression/expression-builder.ts, src/expression/expression-wrapper.ts, src/expression/expression.ts, src/helpers/mssql.ts, src/helpers/mysql.ts, src/helpers/postgres.ts, src/helpers/sqlite.ts, src/kysely.ts, src/migration/migrator.ts, src/operation-node/operation-node-transformer.ts, src/plugin/camel-case/camel-case-plugin.ts, src/plugin/immediate-value/immediate-value-transformer.ts, src/plugin/kysely-plugin.ts, src/plugin/parse-json-results/parse-json-results-plugin.ts, src/plugin/with-schema/with-schema-transformer.ts, src/query-builder/aggregate-function-builder.ts, src/query-builder/delete-query-builder.ts
Hey 👋
This PR fixes some erroneous JSDocs, and also adds some examples.
=> chore: fix jsdoc errors and add some examples, pt. 3.

deno.check.d.ts, src/helpers/postgres.ts, src/operation-node/merge-query-node.ts, src/operation-node/operation-node-transformer.ts, src/query-builder/delete-query-builder.ts, src/query-builder/merge-query-builder.ts, src/query-builder/returning-interface.ts, src/query-builder/update-query-builder.ts, src/query-compiler/default-query-compiler.ts, test/node/src/merge.test.ts, test/typings/test-d/merge.test-d.ts
Hey 👋 
closes #1169.
As of PostgreSQL 17, `MERGE` queries now have `returning` clause support.
=> add `returning` support in `MERGE` queries.

package.json, src/plugin/camel-case/camel-case.ts, test/node/src/camel-case.test.ts
This is my proposed solution to issue #1281 . If there are alternative approaches or suggestions, I would be happy to discuss them.
=> fix: implements a underscore validation to camelcase plugin

src/expression/expression-builder.ts
There's a `.table()` fn, but there's no `.col()` fn. Thought it would be nice to include a reference to `ref` to make discoverability easier.
=> Add a reference to `ref` in `table`'s docstring

src/operation-node/aggregate-function-node.ts, src/operation-node/operation-node-transformer.ts, src/query-builder/aggregate-function-builder.ts, src/query-compiler/default-query-compiler.ts, test/node/src/aggregate-function.test.ts, test/typings/test-d/aggregate-function.test-d.ts
=> Add `within group` clause support for aggregate function builder

src/plugin/with-schema/with-schema-transformer.ts, test/node/src/with-schema.test.ts
Hey :wave:
Recently we've added `eb.fn.jsonAgg` and `eb.fn.toJson`. Both accept table names or `sql.table`/`eb.table` as arguments.
`WithSchemaPlugin` adds schema names to the arguments, resulting in DB errors.
https://onecompiler.com/postgresql/435rdy7de
This makes the plugin unusable anytime such functions are used, which is annoying.
This PR ensures that the plugin leaves `TableNode`s in specific functions' (currently, we know of `jsonAgg` and `toJson`, but there might be more) arguments as-is (no schema is added).
=> fix: `WithSchemaPlugin` is adding schema to table function arguments and causes db errors in `json_agg` and `to_json`.

src/operation-node/join-node.ts, src/parser/expression-parser.ts, src/parser/join-parser.ts, src/query-builder/select-query-builder.ts, src/query-compiler/default-query-compiler.ts, test/node/src/join.test.ts, test/typings/test-d/join.test-d.ts
add outer apply and cross apply.
these are the rough mssql equivalent of left and inner lateral join
[Using Apply](https://learn.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver16#using-apply)
=> Add outer and cross apply (mssql)

src/parser/insert-values-parser.ts, test/node/src/insert.test.ts
=> fix: resolve edge case with varying shapes in multiple item inserts causing `undefined` in parameters.

src/dialect/mssql/mssql-driver.ts, src/dialect/mysql/mysql-driver.ts, src/dialect/postgres/postgres-driver.ts, src/dialect/sqlite/sqlite-driver.ts, src/driver/database-connection.ts, src/index.ts, src/operation-node/operation-node-transformer.ts, src/plugin/camel-case/camel-case-plugin.ts, src/plugin/camel-case/camel-case-transformer.ts, src/plugin/deduplicate-joins/deduplicate-joins-plugin.ts, src/plugin/deduplicate-joins/deduplicate-joins-transformer.ts, src/plugin/handle-empty-in-lists/handle-empty-in-lists-plugin.ts, src/plugin/immediate-value/immediate-value-plugin.ts, src/plugin/immediate-value/immediate-value-transformer.ts, src/plugin/with-schema/with-schema-plugin.ts, src/plugin/with-schema/with-schema-transformer.ts, src/query-builder/delete-query-builder.ts, src/query-builder/insert-query-builder.ts, src/query-builder/update-query-builder.ts, src/query-compiler/compiled-query.ts, src/query-compiler/default-query-compiler.ts, src/query-compiler/query-compiler.ts, src/query-executor/default-query-executor.ts, src/query-executor/query-executor-base.ts, src/schema/create-index-builder.ts, test/node/src/query-id.test.ts, test/node/src/raw-sql.test.ts, test/node/src/test-setup.ts
does what #173 tried to achieve, but in a simpler way as suggested by @koskimas.
- adds `queryId` to `CompileQuery` - now `DatabaseConnection` has access to it in `executeQuery` and `streamQuery` methods in a non-breaking way.
- adds `queryId` as a 2nd optional (for now) argument in all `transform` methods. Now plugins can enjoy even more flexibility - not just in root `transformQuery` and `transformResults` methods.
- exposes `createQueryId` to ease dialect/plugin implementation by 3rd parties.
- also removes `numUpdatedOrDeletedRows` usage as it has been deprecated for 2 years now.
=> add `queryId` to `CompiledQuery` to allow async communication between more components.

CONTRIBUTING.md, package-lock.json, src/dialect/sqlite/sqlite-introspector.ts, test/node/src/introspect.test.ts, test/node/src/test-setup.ts
Fixes: https://github.com/RobinBlomberg/kysely-codegen/issues/105
**Summary:**
- If no `AUTOINCREMENT` is not detected for a table, additionaly checks for `INTEGER PRIMARY KEY`, which sqlite will use to determine whether to autoincrement by default: https://www.sqlite.org/autoinc.html
**Additional Refactor:**
- Changed the `#getTableMetadata` function to execute a total of 2 queries while introspecting the sqlite DB:
**Previously:**
```sql
select name from sqlite_master where type in ('table', 'view') and ...
-- The following 2 queries are repeated for N number of tables returned in first query:
select sql, type from sqlite_master where name = $table
select name, type, notnull, dflt_value from pragma_table_info($table)
```
**Now:**
```sql
select name, sql, type from sqlite_master where …
```
=> fix: isAutoIncrementing: true for sqlite integer primary key

src/migration/migrator.ts
I noticed an incredibly minor typo in a JSDoc comment for the `Migrator` class when scaffolding out a new project, had to fix it real quick.
=> fix(docs): Fixed closing backtick in Migrator JSDoc

src/dialect/sqlite/sqlite-introspector.ts
Minor change to follow up on #1344	
The change to using a `union all` means that although there's now only one query, the query grows to be as long as the number of tables in the DB, which feels a little off.
Decided to see if there was a way to handle this that was a little cleaner and came up with:
```sql
with "table_list" as (
select "name", "sql", "type" from "sqlite_master"
where "type" in ('table', 'view')
and "name" not like 'sqlite_%' order by "name"
)
select
"tl"."name" as "table",
"p"."cid",
"p"."name",
"p"."type",
"p"."notnull",
"p"."dflt_value",
"p"."pk"
from
"table_list" as "tl",
pragma_table_info(tl.name) as "p"
order by "tl.name", "p.cid"
```
Which feels a little nicer than an really large union query
=> refactor: improve sqlite-introspector metadata query

src/query-builder/select-query-builder.ts, test/node/src/select.test.ts
Expands limit in select accepting null value. This PR includes tests.
This PR doesn't add _limit ALL_ : https://github.com/brianc/node-postgres/issues/2673
Closes:
#1345
=> feat: expands limit in select accepting null value

src/dialect/mysql/mysql-driver.ts, src/dialect/postgres/postgres-driver.ts, src/driver/driver.ts, src/kysely.ts, test/node/src/controlled-transaction.test.ts, test/node/src/transaction.test.ts
=> feat: Allow read-only transactions in Postgres and MySQL

site/docs/dialects.md
Hi there! I've built an Oracle dialect and type generator for Kysely. It doesn't support every feature at the moment, but it has most of the basic functionality to enable type safety for querying Oracle Databases. We're using this in our tech stack at Griffiths Waite, and hope to add improvements in the future.
Repository: https://github.com/griffiths-waite/kysely-oracledb
=> Add Oracle dialect to dialects.md

src/driver/runtime-driver.ts, src/util/log.ts, test/node/src/logging.test.ts
Hey :wave:
closes #1380.
Looks like we forgot to also monkey patch streams with logging.
Add an optional (for backwards compatibility) `isStream` log event property.
Went ahead and added differentiation in the logs between regular queries and streamed queries in the default logger.
=> fix: no logging in streams.

src/dialect/mssql/mssql-dialect-config.ts, src/dialect/mssql/mssql-driver.ts, test/node/src/test-setup.ts
Hey :wave:
closes #1061
This PR:
- extracts `validateConnections` to root of MSSQL dialect's config interface. Deprecates old usage (still works, but compile-time errors).
- extracts `resetConnectionsOnRelease` to root of MSSQL dialect's config interface. Deprecates old usage (still works, but compile-time errors). Flips default to `false`.
=> refactor: extract `validateConnections` and `resetConnectionsOnRelease` to root of config, flip default `resetConnectionsOnRelease` behavior.

src/operation-node/create-type-node.ts, src/schema/create-type-builder.ts
Hey :wave:
closes #1118.
This PR makes the `values` argument in `asEnum` a readonly list.
=> feat: create create type as enum values argument readonly.

src/raw-builder/sql.ts
We are trying to support using ANY() with empty arrays such as in this code:
```ts
if (filter.excludedOperatorIds) {
query = query.where(sqlKy`NOT operator_id = ANY(ARRAY[${sqlKy.join(filter.excludedOperatorIds)}])`);
}
if (filter.includedOperatorIds) {
query = query.where(sqlKy`operator_id = ANY(ARRAY[${sqlKy.join(filter.includedOperatorIds)}])`);
}
```
While this code works for any non-empty array, it crashes as the join fails calling a new Array(-1).
This change should maintain the current behavior while supporting empty arrays. If this PR is valid, I can add a test for it.
=> fix: allow empty array for sql.join

src/kysely.ts, src/query-executor/query-executor-base.ts, src/util/provide-controlled-connection.ts
Remove object mutation from controlled transaction.
* Controlled transaction no longer mutates the executor
* Controlled connection no longer mutates the connection
=> Fix ctrl transaction mutation issues

src/query-compiler/default-query-compiler.ts, test/node/src/sql-injection.test.ts
Hey :wave:
closes #1124.
This PR introduces some string literal SQL injection denial in the form of escaping `'` to deny the most common string literal attacks:
```sql
-- when sql.lit(`'; drop table users --`)
where column = ''; drop table users --'
-- when sql.lit(`' or 1=1 --`)
where column = '' or 1=1 --'
```
and make them:
```sql
-- when sql.lit(`'; drop table users --`)
where column = '''; drop table users --'
-- when sql.lit(`' or 1=1 --`)
where column = ''' or 1=1 --'
```
If you find any additional measures we could take, please submit an issue OR swing by the Discord.
Some things are out of bounds, like SQL parsing, semantic checks, etc.
=> feat: escape single quotes in string literals.

src/dialect/postgres/postgres-introspector.ts, test/node/src/introspect.test.ts
Fixes https://github.com/kysely-org/kysely/issues/1425
Does so by wrapping the namespace and relname with the builtin `quote_ident` function to match the behavior of  `pg_get_serial_sequence` lowercasing by default.
Adds a test assertion to the introspector for a `some_table.MixedCaseTable` that I confirmed fails without the fix.
=> pg introspector - Wrap schema.table in double quotes for case handling

src/dialect/sqlite/sqlite-introspector.ts, src/query-builder/order-by-interface.ts
Hey :wave:
closes #1424
Sorry about that. Annoying.
=> fix: SQLite's introspector is printing deprecation errors for `orderBy(array)`.

.github/workflows/preview.yml, .github/workflows/test.yml, package.json
Hey :wave:
Node v18 has reached End of Life on [30.4.2025](https://endoflife.date/nodejs).
This PR removes it from CI and bumps the minimum Node.js engine in `package.json`.
Users should bump Node.js to a version that is still getting security updates. 
Users still on Node v18 can keep using Kysely, but we don't test for them anymore. Last version that was tested for Node v18 is 0.28.2.
=> chore: bye bye node 18.

.github/workflows/test.yml
Hey 👋 
This PR replaces the experimental Node.js v23 with the latest v24 in our CI workflows.
=> chore(CI): replace Node.js v23 with v24.

.github/workflows/test.yml
Hey 👋 
This PR adds `tsgo` (TypeScript native preview) testing to CI. The Go port should have the same behavior as the "old" JavaScript implementation - but let's be safe and get a heads up if something is different.
=> chore(CI): add native typescript type checks.

src/kysely.ts, src/query-builder/delete-query-builder.ts, src/query-builder/insert-query-builder.ts, src/query-builder/merge-query-builder.ts, src/query-builder/select-query-builder.ts, src/query-builder/update-query-builder.ts, src/query-executor/query-executor-base.ts, src/query-executor/query-executor.ts, src/raw-builder/raw-builder.ts, src/schema/alter-table-add-foreign-key-constraint-builder.ts, src/schema/alter-table-add-index-builder.ts, src/schema/alter-table-builder.ts, src/schema/alter-table-drop-constraint-builder.ts, src/schema/alter-table-executor.ts, src/schema/create-index-builder.ts, src/schema/create-schema-builder.ts, src/schema/create-table-builder.ts, src/schema/create-type-builder.ts, src/schema/create-view-builder.ts, src/schema/drop-index-builder.ts, src/schema/drop-schema-builder.ts, src/schema/drop-table-builder.ts, src/schema/drop-type-builder.ts, src/schema/drop-view-builder.ts, src/schema/refresh-materialized-view-builder.ts
Hey :wave:
This PR does some cleanup. `queryId` has been recently added to `CompiledQuery`, but a bunch of places still accept both a `CompiledQuery` and a `queryId` which is redundant.
There's only 1 user-facing place this occurs, and instead of removing the arg, we keep it as optional and log a deprecation message.
=> refactor: remove redundant `queryId` args.

src/kysely.ts, test/node/src/async-dispose.test.ts, test/node/tsconfig.json
=> fix `AsyncDisposable` usage erroring for older TypeScript versions.

src/helpers/mssql.ts, src/helpers/mysql.ts, src/helpers/postgres.ts, src/helpers/sqlite.ts, src/index.ts, src/query-builder/function-module.ts, src/util/type-utils.ts, test/typings/test-d/postgres-json.test-d.ts
Hey :wave:
closes #482.
We're going for a shallow approach - no recursion:
1. Recursion would be very expensive at compile time.
1. JSON results of nested JSON helpers should already be covered by their return type calculation.
1. If you have JSON columns, you should have already defined them properly - no JS/Node native, JSON invalid, types in their `SelectType`.
1. PostgreSQL arrays are in the scope of this change. e.g. a `timestamp[]` column would be `string[]`, not `Date[]`.
Typings test seems to be running for same amount of time. 😬 
Will add some more cases tomorrow.
=> fix(helpers): JSON helpers' return types incorrectly have `Date`s and other JS/Node-native instances that require data type metadata.

.github/workflows/test.yml, test/ts-benchmarks/order-by.bench.ts
Hey 👋 
This PR adds some CI steps to TypeScript benchmarks job, to PR comment the results. This only works when the changes are pushed from this repository, not from a fork.
=> chore(ci): pr comment typescript benchmark results.

site/docs/other-libraries/_category_.json, site/docs/other-libraries/supabase.mdx
Hey :wave:
This PR adds a "Other libraries" section to the docs, with Supabase being the first one.
It's pretty common for Kysely to be used with other libraries, e.g. ORMs, where Kysely is used primarily for querying and the other library takes care of stuff like data modeling, migrations, type generation, etc.
The new section will add visibility to these patterns and the solution we have in our organization or ecosystem.
=> docs: add `kysely-supabase` instructions.

site/docusaurus.config.ts, site/src/css/custom.css
Hey 👋 
This is what co-pilot understood:
This pull request updates how the Poppins font is loaded in the Docusaurus site. Instead of importing the font directly in the CSS, the font is now preloaded and preconnected via `headTags` in the Docusaurus config for improved performance and better loading practices.
**Font loading improvements:**
* Added `headTags` in `site/docusaurus.config.ts` to preconnect to Google Fonts and preload the Poppins stylesheet, optimizing font loading and performance.
* Removed the direct `@import` of the Poppins font from `site/src/css/custom.css`, as font loading is now handled via the config.
=> feat(docs): applying google fonts optimization.

src/expression/expression-builder.ts, test/typings/test-d/expression.test-d.ts
Hey :wave:
closes #891.
This PR makes it so that the following is assignable to `Expression<SqlBool>`:
```ts
eb('age', sql`OP`, 1)
```
Where before it would inherit the type from the first argument, and fail when it was not assignable to `SqlBool` in common contexts.
This was also true when explicitly providing the custom operator a return type.
So now, as an experiment, we'll allow you to dictate the binary expression's return type:
```ts
expectAssignable<Expression<SqlBool>>(eb('age', sql<SqlBool>`OP`, 1)) 
expectAssignable<Expression<number>>(eb('age', sql<number>`OP`, 1))
expectAssignable<Expression<string>>(eb('age', sql<string>`OP`, 1))
```
=> fix(ExpressionBuilder): improper custom operator support in `eb()`.

pnpm-workspace.yaml, src/driver/driver.ts, src/kysely.ts, test/node/src/transaction.test.ts
Hey :wave:
closes #952.
This PR ensures `rollbackTransaction` is only called if `beginTransaction` was successful with a simple flag.
=> fix: auto rollback only if transaction begun.

src/dialect/postgres/postgres-introspector.ts
Fixes #1537.
The issue was that the current `PostgresIntrospector` tries to query information from all tables from all schemas except for `pg_*` schemas, `information_shema` and `crdb_internal` schema for CockroachDB.
This adds a check to filter out any schemas that the current user/connection does not have access to.
=> fix: filter schemas the current user does not have access to in postres introspector
